using System.Collections.Generic;
using UnityEngine;
using System.Threading.Tasks;
using Photon.Pun;

public class Player : MonoBehaviourPun, IPunInstantiateMagicCallback
{
    public int score = 0 ; // // í”Œë ˆì´ì–´ ì ìˆ˜ ì—…ë°ì´íŠ¸ ì‹œ í˜¸ì¶œë  í•¨ìˆ˜
    [Header("í”Œë ˆì´ì–´ ì„¤ì •")]
    [SerializeField] private string playerID = ""; // í”Œë ˆì´ì–´ ê³ ìœ  ID
    private static HashSet<int> userPlayerIDs = new HashSet<int>(); // ì‚¬ìš©ëœ í”Œë ˆì´ì–´ ID ëª©ë¡  

    public string name ="í”Œë ˆì´ì–´"; // ìºë¦­í„° ì´ë¦„  
    public float playerSpeed = 15; // í”Œë ˆì´ì–´ ì´ë™ ì†ë„
    public float rotationSpeed = 100; // íšŒì „ ì†ë„  
    public float rigidbodyMass; // Rigidbody ì§ˆëŸ‰ ì„¤ì •  

    [Header("ì»´í¬ë„ŒíŠ¸ ì°¸ì¡°")]
    private Rigidbody rb; // Rigidbody ì°¸ì¡°  
    // private GameObject bodyObject; // í”Œë ˆì´ì–´ body ì˜¤ë¸Œì íŠ¸ ì°¸ì¡°  
    private bool isUIButtonPressed = false; // UI ë²„íŠ¼ ëˆŒë¦¼ ìƒíƒœ ì²´í¬ ë‹¬ë¦¬ê¸°ë•Œ ture

    public GameObject PlaberCanvas; // í”Œë ˆì´ì–´ ìº í¼ìŠ¤

    [Header("ì…ë ¥ ê°’")]
    private Vector2 movementInput; // ì‚¬ìš©ì ì…ë ¥ì— ë”°ë¥¸ ì´ë™ ë°©í–¥  
    private float vertical = 0; // Zì¶• ì…ë ¥ ê°’  
    private float horizontal = 0; // Xì¶• ì…ë ¥ ê°’  

    [Header("ìƒíƒœ ë³€ìˆ˜")]
    private bool hasEntered = false; // ì¶©ëŒ ìƒíƒœ ì²´í¬  
    [SerializeField] private float moveSpeed; //  ê²Œì„í•˜ëŠ” ë™ì•ˆì˜ í”Œë ˆì´ì–´ ì´ë™ì†ë„ 

    [SerializeField] private JoystickCode joystick; // ì¡°ì´ìŠ¤í‹± ***ì¡°ì´ìŠ¤í‹± í´ë˜ìŠ¤ë¥¼ ì°¸ì¡°í•˜ê¸° ë•Œë¬¸ì— ê°œì¸ë³„ ë“¤ì–´ê°€ëŠ” í´ë˜ìŠ¤ëª…ì´ ë‹¤ë¦„ 
 

    
    private void Awake()
    {
        rb = GetComponent<Rigidbody>();
        playerID = GetUniquePlayerID().ToString(); //ëœë¤ê°’ ë¶€ì—¬
        moveSpeed = playerSpeed; 
    }

    private void Start()
    {
        if (photonView.IsMine)
        {
            PlaberCanvas.gameObject.SetActive(true);
        }
        else
        {
            PlaberCanvas.gameObject.SetActive(false);
        }
    }
    public void OnPhotonInstantiate(PhotonMessageInfo info)
    {
        // ì´ ê°ì²´ê°€ ìƒì„±ë  ë•Œ, ë‚´ TagObjectë¥¼ Player ìŠ¤í¬ë¦½íŠ¸ë¡œ ì—°ê²°
        info.Sender.TagObject = this;
    }

    
    // ì‚¬ìš©ì ì…ë ¥ì— ë”°ë¥¸ ì´ë™ ë°©í–¥ì„ ì €ì¥
    // public void OnMove(InputAction.CallbackContext context)
    // {
    //     movementInput = context.ReadValue<Vector2>();
    // }

    void FixedUpdate()
    {
        // ë‹¤ë¥¸ í”Œë ˆì´ì–´ê°€ ì¡°ì‘í•˜ëŠ” ê²½ìš° ì´ë™í•˜ì§€ ì•ŠìŒ
        if (!photonView.IsMine)return;        

        // ì‰¬í”„íŠ¸ or ë²„íŠ¼ ë‹¬ë¦¬ê¸°
        if (Input.GetKey(KeyCode.LeftShift) || isUIButtonPressed) 
        moveSpeed = playerSpeed * 1.5f; else moveSpeed = playerSpeed;

        // ğŸš— 1. ì „í›„ ì´ë™ (Zì¶• ê¸°ì¤€)
        if (joystick.InputVector2.magnitude != 0)  // ì¡°ì´ìŠ¤í‹± ì´ë™
        {
            movementInput = new Vector2(joystick.InputVector2.x, joystick.InputVector2.y);   
        }else if(Input.GetAxisRaw("Horizontal") != 0 || Input.GetAxisRaw("Vertical") != 0) // í‚¤ë³´ë“œ ì´ë™
        {
            movementInput = new Vector2(Input.GetAxis("Horizontal"), Input.GetAxis("Vertical"));
        }else{ // ì•„ë¬´ì…ë ¥ì´ì—†ìœ¼ë©´
            return;
        }

        Vector3 move = transform.forward * movementInput.y * moveSpeed;// rb.AddForce(move, ForceMode.VelocityChange);
        rb.velocity = new Vector3(move.x, rb.velocity.y, move.z); // Yì¶• ì†ë„ëŠ” ìœ ì§€í•˜ë©´ì„œ ì´ë™

        // ğŸš— 2. ì¢Œìš° íšŒì „ (Yì¶• ê¸°ì¤€)
        float turn = movementInput.x * rotationSpeed * Time.fixedDeltaTime;
        Quaternion turnRotation = Quaternion.Euler(0f, turn, 0f);
        rb.MoveRotation(rb.rotation * turnRotation);
    }
    // ë²„íŠ¼ì„ ëˆ„ë¥¼ ë•Œ ì‹¤í–‰ ë‹¬ë¦¬ê¸°,
    public void OnUIButtonDown()
    {
        isUIButtonPressed = true;
    }

    // ë²„íŠ¼ì„ ë—„ ë•Œ ì‹¤í–‰ ê±·ê¸°
    public void OnUIButtonUp()
    {
        isUIButtonPressed = false;
    }
   


    // ê³ ìœ í•œ playerID ìƒì„± í•¨ìˆ˜
    private int GetUniquePlayerID()
    {
        int id;
        do
        {
            //id = Random.Range(1, 3);  // Random.Range(1, 3)ëŠ” 1ê³¼ 2 ë‘ ê°€ì§€ ìˆ«ìë§Œ ìƒì„±  3ê°œ ì´ìƒì˜ Player ê°ì²´ê°€ ì¡´ì¬í•˜ë©´ ì¤‘ë³µ IDë¥¼ í”¼í•  ìˆ˜ ì—†ì–´ì„œ ë¬´í•œ ë£¨í”„ì— ë¹ ì§
            id = Random.Range(1, 1001);  // 1ë¶€í„° 1000 ì‚¬ì´ì˜ ëœë¤ ìˆ«ì ìƒì„± 
        } while (userPlayerIDs.Contains(id));  // ì´ë¯¸ ì‚¬ìš©ëœ IDë¼ë©´ ë‹¤ì‹œ ìƒì„±

        userPlayerIDs.Add(id);  // ìƒˆë¡œ ìƒì„±ëœ IDë¥¼ ì‚¬ìš© ëª©ë¡ì— ì¶”ê°€
        return id;  // ê³ ìœ í•œ ID ë°˜í™˜
    }

    // [PunRPC]
    void OnTriggerEnter(Collider collider)
    {
        if (!photonView.IsMine) return; // ë‚´ í”Œë ˆì´ì–´ ê°ì²´ê°€ ì•„ë‹ˆë©´ ë¬´ì‹œ

        // ê³µê²©ìì˜ PhotonView ì°¾ê¸°
        PhotonView attackerView = collider.GetComponentInParent<PhotonView>();
        if (attackerView == null || attackerView.IsMine) return; // ìê¸° ë¬´ê¸°ë©´ ë¬´ì‹œ

        Debug.Log($"ì¶©ëŒí•œ ì˜¤ë¸Œì íŠ¸ : {collider.gameObject.name}"); // ì¶©ëŒí•œ ì˜¤ë¸Œì íŠ¸ ì´ë¦„ ì¶œë ¥
        // í”Œë ˆì´ì–´ê°€ ì¶©ëŒí•œ ì˜¤ë¸Œì íŠ¸ê°€ "damageSource" íƒœê·¸ë¥¼ ê°€ì§„ ê²½ìš°
        if (collider.CompareTag("damageSource") )
        {
            GameManager gameManager = FindObjectOfType<GameManager>();
            gameManager.ChangeCamera();

            // ì‚¬ë§ UI í™”ë©´       
            GameOver gameOver = FindObjectOfType<GameOver>();
            gameOver.ShowGameOverUI(); // ê²Œì„ ì˜¤ë²„ UI í™œì„±í™”

            // ê´€ì „ ëª¨ë“œë¡œ ì „í™˜
            PhotonNetwork.LocalPlayer.TagObject = null; // í”Œë ˆì´ì–´ë¥¼ ê´€ì „ìë¡œ ì„¤ì •
            PhotonNetwork.LocalPlayer.SetCustomProperties(new ExitGames.Client.Photon.Hashtable { { "IsSpectator", true } });
            
            // gameObject.SetActive(false); // ê²Œì„ ì˜¤ë²„ UIë¥¼ ë¹„í™œì„±í™”
            PhotonNetwork.Destroy(this.gameObject);  // Destroy(gameObject); // í”Œë ˆì´ì–´ ì˜¤ë¸Œì íŠ¸ ì‚­ì œ
        }

    }


}
